// Forge Protocol SDK - Fogo Testnet Configuration
// Generated by realistic deployment

import { PublicKey } from '@solana/web3.js';

export const FOGO_TESTNET_PROGRAM_IDS = {
  FORGE_CORE: new PublicKey('JsrtWuPj5WanmkEYm7KgqmcvSZhBMLexkmZtiuTJAMto'),
  FORGE_CRUCIBLES: new PublicKey('f22Yb3WFbxaToSGuG4UxQNJ31tgb9U5J4KDGZHQYKwEk'),
  FORGE_SPARKS: new PublicKey('y8BDhEco7RaBr8LFmzbHxwy7bEf1vbXeNsudPfMnUXaf'),
  FORGE_SMELTERS: new PublicKey('KHMsnQhLfsYttpNcGwiaWYfE9YdRijxzgRZzD2K4aAub'),
  FORGE_HEAT: new PublicKey('ePXYsYnrBKYZvXQvksss59NJkseoVrQLzyGN1QGJjkFY'),
  FORGE_REACTORS: new PublicKey('zYhCyjtQhkYGyDUHFpyAfj5QJBdDGzqgGZvjqnDYsLbT'),
  FORGE_FIREWALL: new PublicKey('Jfrs2u1vDCWw1uWdkk6TDLmXsWcd49H3a7c6fAAnzwwN'),
  FORGE_ENGINEERS: new PublicKey('fo2V736UjfWe4bYzFfDnnwUbTra1oFiPtfGUWY829XHH'),
} as const;

export const FOGO_TESTNET_CONFIG = {
  RPC_URL: 'https://testnet.fogo.io',
  WALLET_ADDRESS: new PublicKey('78bNPUUvdFLoCubco57mfXqEu1EU9UmRcodqUGNaZ7Pf'),
} as const;
