[package]
name = "forge-crucibles"
version = "0.1.0"
description = "Forge Protocol Crucibles - Token vaults for user deposits"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "forge_crucibles"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.0"
anchor-spl = "0.32.0"
